apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${secret_name}
  namespace: ${argocd_namespace}
spec:
  refreshInterval: ${refresh_interval}
  secretStoreRef:
    name: ${eso_name}
    kind: ClusterSecretStore
  target:
    name: ${secret_name}
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /git/username
  - secretKey: password
    remoteRef:
      key: /git/password